### ISSUE TITLE
Scml to Scml Conversion Breaks

### ISSUE THREAD

**Issue by daviscook477** [skairunner/kanimal-SE#4]
Conversion produces correct scml file but it messes up the image file names.
Example if using `convert -I scml -O scml` then the image files get changed from `A.png` to `A.png.png`

**Comment by skairunner** [comment]
It seems that the .png.png issue doesn't always happen. I'm going to hopefully try and clean up the internal names so it isn't an issue, though.

**Comment by skairunner** [comment]
63901c2 should address this issue. Can you verify that it was fixed?

**Comment by daviscook477** [comment]
Yes it's fixed.
